/** Spanish labels for sell-sheet catalog feature ids (English ids stay canonical). */
export const SPANISH_FEATURE_LABELS: Record<string, string> = {
  "pressure-wash": "Lavado a presión exterior completo",
  "hand-scrape": "Raspado manual de pintura suelta y descascarada",
  "mildew-treatment": "Tratamiento de moho, algas y manchas",
  caulking: "Calafateo de huecos, grietas y juntas",
  "spot-prime": "Imprimación localizada en madera y metal descubierto",
  "full-prime": "Imprimación completa en superficies descubiertas",
  sanding: "Lijado y nivelado para acabado uniforme",
  masking: "Enmascarado y protección de ventanas, jardines y accesorios",
  "interior-protection": "Protección de muebles y pisos interiores",
  "wood-repair": "Reparación menor de madera podrida y masilla",
  "two-coat": "Garantía de aplicación de dos manos",
  "spray-roll": "Rociado y rodillo para cobertura uniforme",
  "trim-accent": "Molduras, persianas y color de acento incluidos",
  "garage-door": "Pintura de puerta de garaje incluida",
  "deck-fence-stain": "Tinte de terraza o cerca como adicional",
  "color-consult": "Consulta profesional de color",
  "warranty-1yr": "Garantía de mano de obra de 1 año",
  "warranty-2yr": "Garantía de mano de obra de 2 años",
  "warranty-5yr": "Garantía de mano de obra de 5 años",
  "warranty-7yr": "Garantía de mano de obra de 7 años",
  "warranty-10yr": "Garantía de mano de obra de 10 años",
  "manufacturer-warranty": "Registro de garantía del fabricante de pintura",
  "written-warranty": "Certificado de garantía por escrito",
  "power-wash-2yr": "Lavado a presión de cortesía a los 2 años",
  "annual-inspection": "Inspección exterior anual",
  "window-cleaning": "Limpieza exterior de ventanas incluida",
  "gutter-cleaning": "Limpieza de canaletas incluida",
  "caulk-inspection": "Inspección de calafateo y sellado al año 1",
  "touch-up-kit": "Kit de retoques para el propietario en el sitio",
  "project-manager": "Gerente de proyecto dedicado",
  "daily-photos": "Fotos diarias del progreso",
  walkthrough: "Recorrido previo y revisión del alcance",
  "final-walkthrough": "Recorrido final con el propietario",
  "priority-scheduling": "Programación prioritaria",
  "mailbox-post": "Pintura de buzón y poste",
  "same-day-cleanup": "Limpieza del sitio el mismo día",
  "weekend-available": "Disponibilidad fines de semana y noches",
};

export const SPANISH_WORKMANSHIP_COVERAGE =
  "Garantía de mano de obra en todas las superficies pintadas";